// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlk3QjK3eBS6fb8_1Wtl28JJcf-aQXDUs',
    appId: '1:818504671190:web:beb4845792e935c82d4e77',
    messagingSenderId: '818504671190',
    projectId: 'chat-app-a2a79',
    authDomain: 'chat-app-a2a79.firebaseapp.com',
    storageBucket: 'chat-app-a2a79.firebasestorage.app',
    measurementId: 'G-7FCPLQ5WBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUVSQ9iAcQorkMju0oj9LVIVzPPr5RgSY',
    appId: '1:818504671190:android:bf6ddf7fedf6485e2d4e77',
    messagingSenderId: '818504671190',
    projectId: 'chat-app-a2a79',
    storageBucket: 'chat-app-a2a79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChlHrEE6tqPCaDTYUFeLOFAC1qlUXeFJI',
    appId: '1:818504671190:ios:12a405959d5765382d4e77',
    messagingSenderId: '818504671190',
    projectId: 'chat-app-a2a79',
    storageBucket: 'chat-app-a2a79.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
